#!/usr/bin/env python3
"""
opportunity_scorer.py — Canonical Appendix B implementation of the ODI
opportunity algorithm. Reads a cleaned survey CSV (real or synthetic),
computes top-2-box importance + satisfaction normalized to 0-10,
applies Opp = Importance + max(Importance - Satisfaction, 0), and
emits a ranked outcome table + the Opportunity Landscape plot.

Usage:
    python opportunity_scorer.py \
        --survey survey-data.csv \
        --outcomes netted-outcomes.csv \
        --out-dir analysis-out/

Optional:
    --competitors product_a,product_b   (computes per-competitor table if sat_<competitor>_<id> columns exist)
    --segment-col segment_id            (computes per-segment scores too if column present)
    --synthetic                         (stamps SYNTHETIC banner on outputs)
"""

import argparse
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


SYNTHETIC_BANNER = (
    "================================================================\n"
    "WARNING: SYNTHETIC DATA — DIRECTIONAL ONLY — DO NOT SHIP\n"
    "Generated by LLM-simulated respondents grounded in public data.\n"
    "Validate with n>=300 real respondents per ODI v2.4.2 Ch 16.\n"
    "================================================================\n"
)


def classify(opp: float, importance: float, satisfaction: float) -> str:
    if satisfaction > importance:
        return "overserved"
    if opp >= 15:
        return "extreme_opportunity"
    if opp >= 12:
        return "low_hanging_fruit"
    if opp >= 10:
        return "worth_considering"
    if importance >= 7.5 and satisfaction >= 7.5:
        return "table_stakes"
    return "appropriately_served"


def top2box(series: pd.Series) -> float:
    """Percent of non-null respondents who rated 4 or 5, on 0-10 scale."""
    valid = series.dropna()
    if len(valid) == 0:
        return float("nan")
    return float((valid >= 4).sum() / len(valid)) * 10.0


def score_outcomes(survey: pd.DataFrame, outcomes: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, outcome_row in outcomes.iterrows():
        oid = outcome_row["id"]
        imp_col = f"imp_{oid}"
        sat_col = f"sat_{oid}"
        if imp_col not in survey.columns or sat_col not in survey.columns:
            print(f"[warn] missing columns for outcome {oid}; skipping", file=sys.stderr)
            continue
        importance = top2box(survey[imp_col])
        satisfaction = top2box(survey[sat_col])
        gap = max(importance - satisfaction, 0)
        opp = importance + gap
        rows.append({
            "outcome_id": oid,
            "job_step": outcome_row.get("job_step", ""),
            "full_statement": outcome_row.get("full_statement", ""),
            "importance": round(importance, 2),
            "satisfaction": round(satisfaction, 2),
            "gap": round(gap, 2),
            "opportunity": round(opp, 2),
            "classification": classify(opp, importance, satisfaction),
            "n_imp_respondents": int(survey[imp_col].notna().sum()),
            "n_sat_respondents": int(survey[sat_col].notna().sum()),
        })
    return pd.DataFrame(rows).sort_values("opportunity", ascending=False).reset_index(drop=True)


def competitive_table(survey: pd.DataFrame, outcomes: pd.DataFrame, competitors: list[str]) -> pd.DataFrame:
    """Per-outcome, per-competitor top-2-box satisfaction. Adds:
        - sat_<competitor> (the per-competitor top-2-box, computed only on respondents who use that competitor)
        - best_competitor_sat
        - twenty_pct_target_sat (best_competitor_sat * 1.2, capped at 10) — the 20%-better aspirational threshold from Ch 22 + Ch 28
    """
    rows = []
    for _, outcome_row in outcomes.iterrows():
        oid = outcome_row["id"]
        base_imp = top2box(survey[f"imp_{oid}"]) if f"imp_{oid}" in survey.columns else float("nan")
        base_sat = top2box(survey[f"sat_{oid}"]) if f"sat_{oid}" in survey.columns else float("nan")
        row = {
            "outcome_id": oid,
            "full_statement": outcome_row.get("full_statement", ""),
            "importance": round(base_imp, 2),
            "satisfaction_overall": round(base_sat, 2),
        }
        per_competitor_sats = []
        for c in competitors:
            col = f"sat_{c}_{oid}"
            if col in survey.columns:
                v = top2box(survey[col])
                row[f"sat_{c}"] = round(v, 2) if not np.isnan(v) else float("nan")
                if not np.isnan(v):
                    per_competitor_sats.append(v)
            else:
                row[f"sat_{c}"] = float("nan")
        if per_competitor_sats:
            best = max(per_competitor_sats)
            row["best_competitor_sat"] = round(best, 2)
            row["twenty_pct_target_sat"] = round(min(10.0, best * 1.2), 2)
        else:
            row["best_competitor_sat"] = float("nan")
            row["twenty_pct_target_sat"] = float("nan")
        rows.append(row)
    return pd.DataFrame(rows)


def wtp_analysis(survey: pd.DataFrame, segment_col: str | None = None) -> dict:
    """Extract WTP percentiles from any column starting with `wtp_`.

    Produces an overall band and per-segment bands (if segment_col is provided).
    The pricing-band output is consumed by /choosestrategy and /exportdeliverables.
    """
    wtp_cols = [c for c in survey.columns if c.startswith("wtp_") and pd.api.types.is_numeric_dtype(survey[c])]
    if not wtp_cols:
        return {"present": False, "reason": "no wtp_* numeric columns in survey"}

    def band(df_: pd.DataFrame) -> dict:
        primary = df_[wtp_cols[0]].dropna()
        if primary.empty:
            return {"n": 0}
        return {
            "n": int(primary.count()),
            "p25": float(primary.quantile(0.25)),
            "median": float(primary.median()),
            "p75": float(primary.quantile(0.75)),
            "p90": float(primary.quantile(0.90)),
        }

    out = {"present": True, "wtp_columns": wtp_cols, "overall": band(survey)}
    if segment_col and segment_col in survey.columns:
        out["per_segment"] = {}
        for seg, sub in survey.groupby(segment_col):
            out["per_segment"][str(seg)] = band(sub)
    return out


def plot_landscape(scored: pd.DataFrame, out_path: Path, synthetic: bool = False):
    fig, ax = plt.subplots(figsize=(10, 8))

    class_colors = {
        "extreme_opportunity":   "#b22234",
        "low_hanging_fruit":     "#e0833a",
        "worth_considering":     "#d8b13a",
        "table_stakes":          "#3a82d8",
        "appropriately_served":  "#9aa1a8",
        "overserved":            "#7a3aad",
    }
    for cls, color in class_colors.items():
        subset = scored[scored["classification"] == cls]
        if len(subset) == 0:
            continue
        ax.scatter(
            subset["satisfaction"], subset["importance"],
            label=cls.replace("_", " "), c=color, s=80, alpha=0.85, edgecolors="white", linewidths=0.8,
        )

    # Diagonal: importance = satisfaction
    ax.plot([0, 10], [0, 10], linestyle="--", color="#888", linewidth=1, label="imp = sat")
    # Opp = 10 line: imp = (sat + 10) / 2 — anything above-left is opp >= 10
    sat_vals = np.linspace(0, 10, 100)
    imp_line = (sat_vals + 10) / 2
    ax.plot(sat_vals, imp_line, linestyle="--", color="#b22234", linewidth=1, label="opp = 10")

    # Label points
    for _, row in scored.iterrows():
        ax.annotate(row["outcome_id"], (row["satisfaction"], row["importance"]),
                    fontsize=7, alpha=0.7, xytext=(3, 3), textcoords="offset points")

    ax.set_xlabel("Satisfaction (top-2-box %, normalized to 0–10)")
    ax.set_ylabel("Importance (top-2-box %, normalized to 0–10)")
    title = "Opportunity Landscape — ODI v2.4.2"
    if synthetic:
        title = "[SYNTHETIC — DIRECTIONAL ONLY] " + title
    ax.set_title(title)
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 10)
    ax.grid(alpha=0.3)
    ax.legend(loc="lower right", fontsize=9)

    if synthetic:
        ax.text(0.5, 0.5, "SYNTHETIC",
                transform=ax.transAxes, fontsize=80, color="#b22234",
                alpha=0.10, ha="center", va="center", rotation=30, weight="bold")

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="ODI opportunity scorer (Appendix B)")
    parser.add_argument("--survey",   required=True, help="cleaned survey CSV")
    parser.add_argument("--outcomes", required=True, help="netted outcomes CSV (Template 3)")
    parser.add_argument("--out-dir",  default="analysis-out", help="output dir")
    parser.add_argument("--competitors", default="", help="comma-separated competitor names (matches sat_<name>_<id> columns)")
    parser.add_argument("--segment-col", default="", help="optional segment column for per-segment scores")
    parser.add_argument("--synthetic", action="store_true", help="stamp SYNTHETIC banner on outputs")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    survey = pd.read_csv(args.survey)
    outcomes = pd.read_csv(args.outcomes)

    # Apply quality filter
    if "quality_flag" in survey.columns:
        before = len(survey)
        survey = survey[survey["quality_flag"].isna() | (survey["quality_flag"] == "")]
        print(f"[info] dropped {before - len(survey)} rows on quality_flag", file=sys.stderr)

    scored = score_outcomes(survey, outcomes)
    scored_path = out_dir / "opportunity_scores.csv"
    if args.synthetic:
        with open(scored_path, "w") as f:
            f.write(SYNTHETIC_BANNER)
            scored.to_csv(f, index=False)
    else:
        scored.to_csv(scored_path, index=False)
    print(f"[ok] {scored_path}")

    landscape_path = out_dir / "opportunity_landscape.png"
    plot_landscape(scored, landscape_path, synthetic=args.synthetic)
    print(f"[ok] {landscape_path}")

    if args.competitors:
        competitors = [c.strip() for c in args.competitors.split(",") if c.strip()]
        comp = competitive_table(survey, outcomes, competitors)
        comp_path = out_dir / "competitive_table.csv"
        if args.synthetic:
            with open(comp_path, "w") as f:
                f.write(SYNTHETIC_BANNER)
                comp.to_csv(f, index=False)
        else:
            comp.to_csv(comp_path, index=False)
        print(f"[ok] {comp_path}")

    if args.segment_col and args.segment_col in survey.columns:
        for seg_id, subset in survey.groupby(args.segment_col):
            seg_scored = score_outcomes(subset, outcomes)
            seg_path = out_dir / f"opportunity_scores_segment_{seg_id}.csv"
            seg_scored.to_csv(seg_path, index=False)
            print(f"[ok] {seg_path}")
            plot_landscape(seg_scored, out_dir / f"opportunity_landscape_segment_{seg_id}.png", synthetic=args.synthetic)

    # WTP analysis
    wtp_out = wtp_analysis(survey, args.segment_col if args.segment_col else None)
    wtp_path = out_dir / "wtp_analysis.json"
    import json as _json
    with open(wtp_path, "w") as f:
        if args.synthetic:
            f.write("// " + SYNTHETIC_BANNER.replace("\n", "\n// "))
            f.write("\n")
        _json.dump(wtp_out, f, indent=2)
    print(f"[ok] {wtp_path}")

    print("\n=== Top 10 opportunities ===")
    print(scored.head(10)[["outcome_id", "importance", "satisfaction", "opportunity", "classification"]].to_string(index=False))
    if wtp_out.get("present"):
        ov = wtp_out["overall"]
        print(f"\n=== WTP band (overall, n={ov.get('n')}) ===")
        print(f"  p25={ov.get('p25')}  median={ov.get('median')}  p75={ov.get('p75')}  p90={ov.get('p90')}")


if __name__ == "__main__":
    main()
