#!/usr/bin/env python3
"""
synthetic_survey_generator.py — Autonomous synthetic respondent panel.

Consumes a personas.json (from the persona-synthesizer agent) and a
survey.json (from /generatesurvey), and produces a synthetic_survey.csv
in the EXACT schema /computescores and /runsegmentation expect.

Each row's 1-5 importance and satisfaction ratings are drawn from
per-bias distributions defined per persona, so that:
  - Different personas produce visibly different rating profiles.
  - Within a persona, n_per_persona rows form a believable spread.
  - Outcome-specific anchors (where a persona has direct evidence)
    override the bias-by-job-step default.

Every output is stamped SYNTHETIC. The pipeline NEVER replaces the real
n=300-600 survey required by the ODI handbook (Ch 16). Use only for:
  1. Stress-testing the survey instrument.
  2. Generating directional opportunity hypotheses.
  3. Prioritizing which real-customer interviews to commission first.

Usage:
    python synthetic_survey_generator.py \
        --personas synthetic-out/personas.json \
        --survey survey-out/survey.json \
        --outcomes netted-outcomes.csv \
        --n-per-persona 60 \
        --out synthetic-out/synthetic_survey.csv
"""

import argparse
import json
import os
import random
from pathlib import Path

import numpy as np
import pandas as pd


SYNTHETIC_BANNER = (
    "# =============================================================\n"
    "# WARNING: SYNTHETIC DATA — DIRECTIONAL ONLY — DO NOT SHIP\n"
    "# Generated by LLM-simulated respondents grounded in public data.\n"
    "# Validate with n>=300 real respondents per ODI v2.4.2 Ch 16.\n"
    "# =============================================================\n"
)


BIAS_TO_DIST = {
    "very_high":   [0.01, 0.04, 0.10, 0.30, 0.55],   # P(1..5)
    "high":        [0.02, 0.08, 0.20, 0.35, 0.35],
    "med":         [0.05, 0.20, 0.35, 0.25, 0.15],
    "low":         [0.20, 0.40, 0.25, 0.10, 0.05],
    "very_low":    [0.40, 0.40, 0.13, 0.05, 0.02],
}


def draw(bias_label: str, rng: np.random.Generator) -> int:
    dist = BIAS_TO_DIST.get(bias_label, BIAS_TO_DIST["med"])
    return int(rng.choice([1, 2, 3, 4, 5], p=dist))


def perturb_numeric(value, pct: float, rng):
    if not isinstance(value, (int, float)):
        return value
    if value is None:
        return value
    delta = rng.uniform(-pct, pct) * value
    return type(value)(max(0, value + delta))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--personas",      required=True)
    parser.add_argument("--survey",        required=True)
    parser.add_argument("--outcomes",      required=True)
    parser.add_argument("--n-per-persona", type=int, default=60,
                        help="Sampled rows per persona. Adds within-persona noise; does NOT add statistical independence. The real upper bound on the synthetic run's statistical power is the persona count, not this number.")
    parser.add_argument("--out",           required=True)
    parser.add_argument("--seed",          type=int, default=42)
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    personas = json.load(open(args.personas))["personas"] if "personas" in json.load(open(args.personas)) else json.load(open(args.personas))
    if isinstance(personas, dict) and "personas" in personas:
        personas = personas["personas"]

    survey = json.load(open(args.survey))
    outcomes = pd.read_csv(args.outcomes)

    profile_factors = []
    for item in survey["sections"].get("profiling", []):
        factor_name = item.get("factor_name") or item["id"]
        profile_factors.append(factor_name)

    rows = []
    counter = 0
    for persona in personas:
        pid = persona["id"]
        imp_bias_by_step = persona.get("importance_bias", {})
        sat_bias_by_step = persona.get("satisfaction_bias", {})
        outcome_anchors = {a["outcome_id"]: a for a in persona.get("outcome_specific_anchors", [])}
        cf_profile = persona.get("complexity_factor_profile", {})

        for r_i in range(args.n_per_persona):
            counter += 1
            row = {
                "respondent_id": f"SYN-{pid}-{r_i+1:04d}",
                "persona_id": pid,
                "screener_pass": 1,
                "quality_flag": "",
            }
            # profiling values (perturbed)
            for factor in profile_factors:
                v = cf_profile.get(factor)
                if isinstance(v, (int, float)):
                    row[f"profile_{factor}"] = perturb_numeric(v, 0.10, rng)
                else:
                    row[f"profile_{factor}"] = v

            for _, outcome_row in outcomes.iterrows():
                oid = outcome_row["id"]
                step = outcome_row["job_step"]
                # outcome-specific anchor wins; else use bias-by-step
                if oid in outcome_anchors:
                    imp_bias = outcome_anchors[oid].get("imp", "med")
                    sat_bias = outcome_anchors[oid].get("sat", "med")
                else:
                    imp_bias = imp_bias_by_step.get(step, "med")
                    sat_bias = sat_bias_by_step.get(step, "med")

                # 3% don't-know on outcomes without anchor
                if oid not in outcome_anchors and rng.random() < 0.03:
                    row[f"imp_{oid}"] = None
                else:
                    rating = draw(imp_bias, rng)
                    # 5% drift noise
                    if rng.random() < 0.05:
                        rating = max(1, min(5, rating + rng.choice([-1, 1])))
                    row[f"imp_{oid}"] = rating

                if oid not in outcome_anchors and rng.random() < 0.03:
                    row[f"sat_{oid}"] = None
                else:
                    rating = draw(sat_bias, rng)
                    if rng.random() < 0.05:
                        rating = max(1, min(5, rating + rng.choice([-1, 1])))
                    row[f"sat_{oid}"] = rating

            # WTP — band-based
            wtp_band = persona.get("willingness_to_pay_band", "med")
            wtp_centroid = {"low": 5, "med": 15, "high": 35}.get(wtp_band, 15)
            row["wtp_q1"] = int(max(0, rng.normal(wtp_centroid, wtp_centroid * 0.3)))
            row["wtp_q2"] = int(row["wtp_q1"] * rng.uniform(1.1, 1.5))
            row["wtp_q3"] = draw(persona.get("willingness_to_pay_band", "med"), rng)

            row["completion_min"] = round(float(rng.normal(28, 4)), 1)
            rows.append(row)

    df = pd.DataFrame(rows)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(SYNTHETIC_BANNER)
        df.to_csv(f, index=False)
    print(f"[ok] {out_path} — {len(df)} synthetic rows from {len(personas)} personas")
    print(f"[!] These are NOT real respondents. Field n>=300 real humans before any decision.")


if __name__ == "__main__":
    main()
